<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-QJ8FI0G" ignored="0" name="Validate Free Price" tests="2" failures="2" timestamp="25 Jun 2020 18:11:39 GMT" time="77.826" errors="0">
  <testcase name="tc2_getPriceUnderFeaturedCourses" time="53.134" classname="testcases.tc_validateFreePrice">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="1">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 1
at testcases.tc_validateFreePrice.tc2_getPriceUnderFeaturedCourses(tc_validateFreePrice.java:48)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- tc2_getPriceUnderFeaturedCourses -->
  <testcase name="tc2_getPriceUnderFeaturedCourses" time="55.444" classname="testcases.tc_validateFreePrice">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at testcases.Listeners.onTestFailure(Listeners.java:45)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
... Removed 13 stack frames]]>
    </failure>
  </testcase> <!-- tc2_getPriceUnderFeaturedCourses -->
</testsuite> <!-- Validate Free Price -->
